[package]
name = "lingy"
version = "0.0.1"
edition = "2021"
description = "A Clojure for Rust"
license = "MIT"
readme = "ReadMe.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
